export const actionType = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE', 

    UPLOAD_IMAGES: 'USER_UPLOAD_IMAGES', 

    RE_RENDER_COMPONENT : 'RENDER_COMPONENT',
    RE_RENDER_USER_AMT : 'RE_RENDER_USER_AMT',
    RE_RENDER_GROUP_COMP : 'RE_RENDER_GROUP_COMP',
    RE_RENDER_BOUNTY_COMP : 'RE_RENDER_BOUNTY_COMP',
    PUSH_NOTIFICATION : 'SHOW_PUSH_NOTIFICATION',
    ONETIME_PUSH_NOTIFICATION : 'ONETIME_PUSH_NOTIFICATION',
    SEND_FRIEND_REQUEST : 'USER_SEND_FRIEND_REQUEST',
    CANCEL_FRIEND_REQUEST : 'USER_CANCEL_FRIEND_REQUEST',

    DRAFT_COUNT : 'USER_DRAFT_COUNT',
    ADD_CITY : 'ADD_CITY',
    GET_CITY : 'GET_CITY',
    GET_RELASHIP : 'GET_RELASHIP',

    GET_PHONENO : 'GET_PHONENO',
    ADD_PHONENO : 'ADD_PHONENO',
    EDIT_USER_DETAIL : 'EDIT_USER_DETAIL',

    CLOSE_DESC_FORM : 'CLOSE_DESC_FORM',
    CLOSE_ADDRESS_FORM : 'CLOSE_ADDRESS_FORM',
    CLOSE_EDUCA_FORM : 'CLOSE_EDUCA_FORM',
    CLOSE_PROFESS_FORM : 'CLOSE_PROFESS_FORM',
    CLOSE_WORKPLACE_FORM : 'CLOSE_WORKPLACE_FORM',
    CLOSE_RELATIONSHIP_FORM : 'CLOSE_RELATIONSHIP_FORM',
    CLOSE_PHONO_FORM : 'CLOSE_PHONO_FORM',

    GET_ALL_COMMUNITIES : 'GET_ALL_COMMUNITIES',
    ADD_COMMUNITY : 'ADD_COMMUNITY',
    SEND_COMMUNITY : 'SEND_COMMUNITY',

    GET_SINGLE_COMMUNITY : 'GET_SINGLE_COMMUNITY',
    GET_ALL_STATES : 'GET_ALL_STATES',
    GET_CITY_BY_STATEID : 'GET_CITY_BY_STATEID',

    GET_ALL_PROFESSIONS : 'GET_ALL_PROFESSIONS',

    DELETE_ABOUT_DETAIL : 'DELETE_ABOUT_DETAIL',
    PHONE_COUNTRY_CODE_LIST : 'PHONE_COUNTRY_CODE_LIST',

    FILTER_POST_TYPE : 'FILTER_POST_TYPE',
    SET_USER_FLAG : 'SET_USER_FLAG',
    SEARCH_POST_USERDB : 'SEARCH_POST_USERDB',
    SEARCH_POST_HOMEPG : 'SEARCH_POST_HOMEPG',

    ACCORDION_ACTION : 'ACCORDION_ACTION',

    USER_AMT : 'USER_AMT',
    POST_PRICE : 'POST_PRICE',
    USER_GROUP_NAMES : 'USER_GROUP_NAMES',
    SHOW_HIDE_CREATE_GP_FORM : 'SHOW_HIDE_CREATE_GP_FORM',
    INITIAL_MULTISELECT : 'INITIAL_MULTISELECT',
    USER_TYPE : 'USER_TYPE',
    USER_LEVEL_CHANGE : "USER_LEVEL_CHANGE",
    USER_LEVEL_PAY_BOX : "USER_LEVEL_PAY_BOX",
    USER_SUBSC_POST_DETAILS : "USER_SUBSC_POST_DETAILS",
    USER_SUBSC_POST_DURATION :"USER_SUBSC_POST_DURATION",
    USER_TIPPTRADE_POINT : "USER_TIPPTRADE_POINT",
    PAYMENT_TYPE_SELECT_MODAL : "PAYMENT_TYPE_SELECT_MODAL",
    CHECKED_ADD_TIPP_POINT : 'CHECKED_ADD_TIPP_POINT',
    SHARE_POST_WITH_FRIEND : 'SHARE_POST_WITH_FRIEND',
    ADVANCE_POST_SHARE_SETTING : "ADVANCE_POST_SHARE_SETTING",
    ALL_FRIEND_CLIENT_DISPLAY_DIALOG_BOX :  "ALL_FRIEND_CLIENT_DISPLAY_DIALOG_BOX",
    RE_RENDER_HOME_COMP:"RE_RENDER_HOME_COMP"
};